### ISSUE TITLE
Decide on Beaglebone

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/podiv-altium#11]
Issue for discussion on the beaglebone vs. other processing options.

**Comment by rcastle1** [comment]
i don't really have a stake in the the outcome of this discussion, but it's been going on for over a month and needs to be decided.

**Comment by rcastle1** [comment]
What model beaglebone are you using @ezraboley ?

**Comment by ezraboley** [comment]
[BeagleBone Black Rev C w/o wireless](https://github.com/beagleboard/beaglebone-black/wiki/System-Reference-Manual)
