### ISSUE TITLE
Change out LEDs

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/podiv-altium#24]
![leds](https://user-images.githubusercontent.com/25836359/46517273-5fb66680-c823-11e8-9934-2e69122185dd.PNG)

Should be a fairly quick project but it will walk you through all of the steps of making changes to a schematic in our workflow. 

In the past we've had to pull out the oscilloscope to tell if CAN messages are sending. LED indicators will let us visually know that messages are sending/receiving. Unfortunately, I only have Red and Green LEDs, which usually indicate something right or wrong is happening, but in this scenario, sending/receiving may or may not always follow that binary, so I want to switch these LEDs to a neutral colors (orange and blue, although if you really want to pick a different color that's fine)

1. Spec out Orange and blue SMD LEDs (0603 preferabbly, check for a some that are in the same package as the existing green/red LEDs)
2. Add these parts to the library branch (including component links, 3D Models (color them too please!))
3. Make a pull request, get it approved
4. Rebase the beaglebone_project
5. Update the schematic with the appropriately colored LEDs
6. Commit, push changes. Don't make a Pull request here are this project is still ongoing, but push to remote so I can get the changes.

**Comment by vkottler** [comment]
I think we want these normally DNP also

**Comment by btobin86** [comment]
Submitted a pull request for the orange and blue LED components that were added to the schematic and footprint libraries

**Comment by rcastle1** [comment]
what branch did you do this on?

**Comment by btobin86** [comment]
Originally on libraries, but then you told me to move put it on
beaglebone_2 instead.

**Comment by rcastle1** [comment]
complete. thanks
