### ISSUE TITLE
TEMPLATE: Retroreflective Sensor

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/podiv-altium#28]
### Note: 
See the Hyperloop Test Track Specification document in box (Badgerloop eyes only) located [here](https://uwmadison.box.com/s/ezaj20bkuyem90ak4xtz95dnn90fkpr2) for more information on navigation. 

### Purpose: 
The [QMIC](https://www.automationdirect.com/adc/Shopping/Catalog/Sensors_-z-_Encoders/Photoelectric_Sensors/DC_Rectangular/Retroreflective_(QM-z-CX-z-FE_Series)/QMIC-0N-0A) ([Datasheet](https://cdn.automationdirect.com/static/specs/peminirectqm.pdf) retroreflective sensor detects tape strips throughout the tube and triggers an interrupt input to the beaglebone. We calculate our position, velocity and acceleration from the retroreflective tape strip count. Once this is up and running, we will add in interpolation from the IMU for higher resolution. 

### Circuit Description:
The QMIC photoelectric sensor is an NPN output type powered from 9-36V. The sensor could be powered from either LV Battery or 24V. It may be advantageous to use 24V as a constant source. When the circuit is active (i.e. tape is detected) the current will flow through the current limiting resistor and activate the optocoupler. This effectively converts the higher voltage signal into a low voltage signal that is able to be read in by the beaglebone. 

You will need to also investigate the interrupt capability of the beaglebone. We have all of the circuitry for this circuit on hand an in through hole form, so you should also build the circuit and test it out. It would be great to work with @ezraboley or @ethanlink17 to write some code to verify the compatibility with the beaglebone. 

### Pod III Schematic:
![retro](https://user-images.githubusercontent.com/25836359/46577477-243fa780-c99d-11e8-88e7-8f26bca9b4e2.PNG)

Full [Navigation Schematic](https://uwmadison.box.com/s/fuog5mmjrutf7e8z87q4elr5liqnag0e)

**Comment by keegangruss88** [comment]
I made this for the new project list. I need to spec out the parts and make the footprint yet.
