### ISSUE TITLE
TEMPLATE: Accelerometer

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/podiv-altium#29]
### Purpose:
Acceleration measurement and velocity interpolation. 

### Circuit Description
This one's not too bad circuit wise. This basically requires a breakout to the [MTI-3](https://www.digikey.com/product-detail/en/xsens-technologies-bv/MTI-3-DK/MTI-3-DK-ND/5325385) Sensor. Actual mounting of the sensor is a little more tricky. We'd like the sensor to be mounted directly on the PCB as opposed to a short harness. Although, having the ability to adjust the sensor so it can line up with the direction of travel in the pod would be good. It's up to the RE. 

### Pod III Schematic 
![capture](https://user-images.githubusercontent.com/25836359/46578462-a9cf5180-c9b5-11e8-9bab-b978b67fd415.PNG)
Full Navigation [Schematic](https://uwmadison.box.com/s/fuog5mmjrutf7e8z87q4elr5liqnag0e)

**Comment by vkottler** [comment]
I think deciding what interface to expose for use with the proposed module architecture is going to be hard to do right now, this issue can just encapsulating upstreaming a high-quality schematic symbol and footprint.

**Comment by btobin86** [comment]
Pushed the schematic symbol and breakout board schematic
