### ISSUE TITLE
TEMPLATE: LV Battery Monitoring 

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/podiv-altium#34]
### Purpose: 
While not as dangerous as the high voltage pack, the low voltage battery still needs to be monitored to ensure that it doesn't go into thermal runaway, catch on fire, or operate out of it's datasheet specifications. 

### Circuit Description:
* Temperature Monitoring: Thermistor circuit
* Voltage Monitoring: Could go in a few different directions here. Simplest option is a voltage divider, although we could use a battery monitor IC for this. 
* Current Monitoring: The INA240A Sensor would be useful for a current measurement. This is basically a voltage measurement across a shunt resistor that gets amplified. The INA240 series can have the gain be 50, 100, 200 I believe. When specing a power resistor for the shunt, you have to make sure that the power rating of the resistor (Given in watts) is greater than the power through the resistor (I^2*R losses)

**Comment by btobin86** [comment]
Thermistor resistance and output voltage are representative as variable functions. The resistance value for the fixed resistor in the series was determined by finding the resistance of the thermistor at a T at a midpoint of the stated T operating range (-40 degrees ~ 125 degrees), and then setting it equal to that. I also read, however, that you can set it to the resistance value of R25. I will do testing with this sometime this week to judge the accuracy of the circuit's reading.

**Comment by rcastle1** [comment]
Closing
