### ISSUE TITLE
Op Amp Math

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/podiv-altium#36]
![op amp](https://user-images.githubusercontent.com/25836359/46783878-d1d5f200-cce0-11e8-97db-e25a9d44917b.PNG)
If anyone wants to do some op-amp math that'd be cool. Need to amplify that output of the NPP pressure sensor to 0-50mV scale to 0 to 3.3V

**Comment by nat950** [comment]
I have the Op-Amp math. As long as Rf (R5 in the schematic) is 66 times as large as Rg(R6 in the schematic), an output from 0 - 3.3V should be obtained. A 100 ohm resistor for R6 and 6.6K ohm resistor for R5 may be the easiest way to do this.

**Comment by vkottler** [comment]
What thing is going to be sampling `PRESS1_OUT`?

**Comment by rcastle1** [comment]
@vkottler Beaglebone Input. 

Closing
