### ISSUE TITLE
Power Supplies -- 3.3V Rail

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/podiv-altium#4]
Rough Requirements:
5A Supply
+- 5%
Input Voltage 10-15V
Utilizing the LTC8642S

**Comment by vkottler** [comment]
5A on a 3.3V rail seems like a lot, we probably want to look at some of the block-level components we expect and see and maybe go with a less heavy-handed solution (unless you already have a good idea of where that requirement comes from)

**Comment by rcastle1** [comment]
Switched to using the LT8650S for 5 and 3.3V rails. Schematic capture complete
