### ISSUE TITLE
HV_IO Breakout

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/podiv-altium#60]
@shelby noticed that I (stupidly) didn’t breakout the shutdown circuit lines to the DSub. Issue was resolved by connecting 18 awg wire to the underside of the PTH on the jumper to the PTH on the dsub. This is all just 12V <0.5A to drive the contactor, so this solution should be ok. All wiring is on the bottom side of the board too ;)

@Shelby can you comment with the updated pinout? 

If the board is REVed, add breakouts.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rcastle1** [comment]
@dawiggleman ^

**Comment by dawiggleman** [comment]
Yes,
Connector J4B:
Pin 13: Inertia Switch +
Pin 14: Inertia Switch -
Pin 17: Master/E-Stop Switch +
Pin 18: Master/ E-Stop Switch -

**Comment by rcastle1** [comment]
Thanks. Were you able to test this out? I saw the rework today

**Comment by rcastle1** [comment]
Will be resolved in REVB

**Comment by rcastle1** [comment]
Board is assembled, in queue for validation. 

(this got sidetracked due to other priorities due to reveal. Aiming to have board validated by 4/24)

**Comment by rcastle1** [comment]
Rev B functioning as expected.
